---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r Load the necessary libraries, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#load libraries
library(coxme)
library(ggplot2)
library(here)
library(metacsv)
library(viridis)
library(readxl)
library(survminer)
library(tidyverse)
```


```{r Read in data and begin manipulating, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#set directory, read in file
setwd("C:/Users/Danielle.Perez/Documents/Krill 2019/krillSurvival/data")
d <- read_excel("Krill Data.xlsx")
#d <- readxl::read_xlsx(here)

#Manipulate calendar date, adds "day" column
d$DateOfPresPOSIX <- as.POSIXlt.character("2019-9-12")
d$Day <- difftime(d$Date ,d$DateOfPresPOSIX , units = c("days"))
d$Day <- round(d$Day)

#Creates a data frame of MOATS and corresponding number of beginning krill
moatStart <- data.frame(Moats = c(1:8,10:13), nStart = c(85,85,80,80,80,80,80,80,80,80,80,80))

#Creates vector for alive actually observed at the end of the experiment
moatStart$aliveObserved <- c(28,17,11,8,27,16,26,16,31,8,12,15)

#Expected alive based on number of mort counts tabulated during the experiment
moatStart$aliveExpected <- c(44,33,23,37,49,24,38,26,52,27,28,46)

#Missing krill based on expected vs. observed live at the end
moatStart$missing = moatStart$aliveExpected - moatStart$aliveObserved

#Frame for tabulating every krill, every observation day
dfFull <- data.frame(Moats = character(0), KrillID = character(0), Day  = numeric(0),
                      confirmedDeath = numeric(0), assumedDeath = numeric(0),
                     confirmedDeathEvent = numeric(0),assumedDeathEvent = numeric(0))
```

```{r All the functions, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#Create a data frame row in dfFull for every Krill, every observation day, fill it with applicable 
# MOATS number, Krill ID (based on MOATS number and number of total initial Krill), observation day index,
# and placeholder values for whether or not they were confirmed or assumed dead on each observation day
for (i in moatStart$Moats){
  for (j in 1:moatStart$nStart){
    for(k in unique(d$Day)){
      dTemp <- data.frame(Moats = i, KrillID = sprintf("%d-%d",i,j), Day = k, confirmedDeath = 0, assumedDeath = 0,
                          confirmedDeathEvent = 0, assumedDeathEvent = 0)
      dfFull <- rbind(dfFull,dTemp)
    }
  }
}

# Loop through all MOATS on all observation days and kill the krill depending on the number of morts observed on the day
for (i in moatStart$Moats){
  for (j in unique(d$Day)){
    dMoatDay <- d[d$Moats == i & d$Day == j,]
    undeadMD <- dfFull$KrillID[dfFull$Moats == i & dfFull$Day == j & dfFull$confirmedDeath == 0]
    if (dMoatDay$Morts != 0) {
      for (k in 1:dMoatDay$Morts){
        dfFull$confirmedDeath[dfFull$KrillID == undeadMD[k] & dfFull$Day >= j] <- 1
        dfFull$confirmedDeathEvent[dfFull$KrillID == undeadMD[k] & dfFull$Day == j] <- 1
      }
    }
  }
}

#Loop through all MOATS to distribute the missing krill as deaths based on the relative weighting of the day's death count
# to the total death count for a given MOATS. Only kill krill that have no recorded confirmedDeath assigned above.
for (i in moatStart$Moats){
  totalMoatDeaths <- sum(d$Morts[d$Moats == i])
  assumedMoatTotalDeaths <- 0
  
  idxDeadliestMoatDay <- which.max(d$Morts[d$Moats == i])
  allMoatDays <- d$Day[d$Moats == i]
  deadliestMoatDay <- allMoatDays[idxDeadliestMoatDay]
  
  for (j in unique(d$Day)){
    assumedMoatDayDeaths <- round(moatStart$missing[moatStart$Moats == i] * d$Morts[d$Moats == i & d$Day == j]/totalMoatDeaths) 
    assumedMoatTotalDeaths <- assumedMoatTotalDeaths + assumedMoatDayDeaths
    undeadMD <- dfFull$KrillID[dfFull$Moats == i & dfFull$Day == allMoatDays[length(allMoatDays)] & dfFull$confirmedDeath == 0 & dfFull$assumedDeath == 0]  
    if (assumedMoatDayDeaths != 0){
      for (k in 1:assumedMoatDayDeaths){
        dfFull$assumedDeath[dfFull$KrillID == undeadMD[k] & dfFull$Day >= j] <- 1
        dfFull$assumedDeathEvent[dfFull$KrillID == undeadMD[k] & dfFull$Day == j] <- 1
      }
    }
  }
  
  # Check to see if we under or overkilled based on the rounding
  if (moatStart$missing[moatStart$Moats == i] != assumedMoatTotalDeaths) {
    # sprintf("MOATS %d has %d missing and %d assumed dead. Correcting...\n",i,
    #         moatStart$missing[moatStart$Moats == i],assumedMoatTotalDeaths)
    deathCorrection <- moatStart$missing[moatStart$Moats == i] - assumedMoatTotalDeaths
    if (deathCorrection > 0){ #underkill, need to kill more of what's undead on the deadliest day
      undeadMDeadliest <- dfFull$KrillID[dfFull$Moats == i & dfFull$Day == deadliestMoatDay &
                                           dfFull$confirmedDeath == 0 & dfFull$assumedDeath == 0]
      for (k in 1:deathCorrection){
        dfFull$assumedDeath[dfFull$KrillID == undeadMDeadliest[k] & dfFull$Day >= deadliestMoatDay] <- 1
        dfFull$assumedDeathEvent[dfFull$KrillID == undeadMDeadliest[k] & dfFull$Day == deadliestMoatDay] <- 1        
      }
      } else if (deathCorrection <0){ #overkill, need to resurrect the last ones killed on the deadliest day, starting with the last
        deadMDeadliest <- dfFull$KrillID[dfFull$Moats == i & dfFull$Day == deadliestMoatDay & 
                                           dfFull$assumedDeathEvent == 1]
        for (k in 0:(abs(deathCorrection)-1)) {
          dfFull$assumedDeath[dfFull$KrillID == deadMDeadliest[length(deadMDeadliest) - k] & dfFull$Day >= deadliestMoatDay] <- 0
          dfFull$assumedDeathEvent[dfFull$KrillID == deadMDeadliest[length(deadMDeadliest) - k] & dfFull$Day == deadliestMoatDay] <- 0
        }
    }
  }
}
```

```{r A few more tweaks, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#Create total deaths and total death events columns to combine the observed and weighted deaths
dfFull$totalDeath <- as.integer(as.logical(dfFull$confirmedDeath | dfFull$assumedDeath))
dfFull$totalDeathEvent <- as.integer(as.logical(dfFull$confirmedDeathEvent | dfFull$assumedDeathEvent))


#Add treatment column, assigning treatments to corresponding MOATS
dfFull$treatment <- ""
dfFull$treatment[dfFull$Moats==4| dfFull$Moats==5] <- "Ambient"
dfFull$treatment[dfFull$Moats==1 | dfFull$Moats==6| dfFull$Moats==11] <- "HighTemp"
dfFull$treatment[dfFull$Moats==3 | dfFull$Moats==7| dfFull$Moats==10|dfFull$Moats==12] <- "Current"
dfFull$treatment[dfFull$Moats==2 | dfFull$Moats==8| dfFull$Moats==13] <- "AllChange"

#Now we need to only include MOATS 3 until Day 42 because things got weird then. But there are still good data, so we'll keep a lot
#If it died before day 42, it's for real dead. If it was alive on day 42, it gets a 0 and we don't care what happened after that
dfFull$Day[dfFull$Moats == 3 & dfFull$Day >= 42] <- 42 - 1
dfFull$confirmedDeath[dfFull$Moats == 3 & dfFull$Day >= 42] <- 0
dfFull$confirmedDeathEvent[dfFull$Moats == 3 & dfFull$Day >= 42] <- 0

#Surv and Survfit like only to know the deathday and that something lived until the end, so pare down the
# full tracking dataframe to that information only

dfDeathDaysOnly <- dfFull[dfFull$confirmedDeathEvent == 1 | dfFull$assumedDeathEvent == 1,]
dfSurvived <- dfFull[dfFull$Day == allMoatDays[length(allMoatDays)] & 
                       dfFull$confirmedDeath == 0 & dfFull$assumedDeath == 0,]

dfEventsOnly <- data.frame(Moats = character(0), KrillID = character(0), Day  = numeric(0),
                     confirmedDeath = numeric(0), assumedDeath = numeric(0),
                     confirmedDeathEvent = numeric(0),assumedDeathEvent = numeric(0),
                     totalDeath = numeric(0), totalDeathEvent = numeric(0), 
                     treatment = character(0))
dfEventsOnly <- rbind(dfEventsOnly,dfDeathDaysOnly,dfSurvived)

#Try it with either dfFull or dfEventsOnly; it looks the least wrong with dfEventsOnly, and with all the Surv
# events = $confirmedDeathEvents or $assumedDeathEvents
df <- dfEventsOnly
```

```{r Survival by MOATS, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#Confirmed Deaths
survCon <- Surv(time = df$Day, event = df$confirmedDeathEvent, type = "right")
sfConAllTimeM <- survfit(survCon ~ Moats, df)

#Assumed Deaths
survWeight <- Surv(time = df$Day, df$assumedDeathEvent, type = "right")
sfWeightAllTimeM <- survfit(survWeight ~ Moats, df)

#Total Deaths
survTotal <- Surv(time = df$Day, df$totalDeathEvent, type = "right")
sfTotalAllTimeM <- survfit(survTotal ~ Moats, df)

#Plot just the confirmed deaths from the beginning
ggsurvplot(sfConAllTimeM, data = df, title = "All Confirmed Deaths, All MOATS, All Time")

#Plot all confirmed and assumed deaths from the beginning, but keep them separated
fitAllTimeM <- list(S1 = sfConAllTimeM, S2 = sfWeightAllTimeM)
gpAllTimeM <- ggsurvplot(fitAllTimeM, data = df, combine = TRUE,
                 risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                 censor = FALSE, size = 1.5, legend = "none",
                 xlab = "Time in days",ylab = "Survival Probability",
                 title = "All Confirmed and Assumed Deaths (separate) All MOATS, All Time")
lines <-  c(rep(c("solid"),12),rep(c("dotted"),12))
gpAllTimeM$plot <- gpAllTimeM$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 25, y = 1.05, label = "Solid = Confirmed; Dotted = Assumed; Color group by MOATS")
gpAllTimeM

#Plot all confirmed and assumed deaths from the beginning, but put them together
fitTotalM <- list(S1 = sfConAllTimeM, S2 = sfTotalAllTimeM)
gpTotalM <- ggsurvplot(fitTotalM, data = df, combine = TRUE,
                                  risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                                  censor = FALSE, size = 1.5, legend = "none",
                                  xlab = "Time in days",ylab = "Survival Probability",
                                  title = "All Confirmed & Assumed Deaths, All MOATS, All Time")
lines <-  c(rep(c("solid"),12),rep(c("dotted"),12))
gpTotalM$plot <- gpTotalM$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 30, y = 1, label = "Solid = Confirmed; Dotted = Confirmed+Assumed; Color group by MOATS")
gpTotalM

#Adjust for acclimation time, remove problematic MOATS and plot again
dfAccl <- df[df$Day > 10,]
dfAcclGoodMoats <- subset(dfAccl, Moats != 4 & Moats != 5 & Moats != 11)

survConAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$confirmedDeathEvent, type = "right")
sfConAcclM = survfit(survConAccl ~ Moats, dfAcclGoodMoats)

survWeightAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$assumedDeathEvent, type = "right")
sfWeightAcclM = survfit(survWeightAccl ~ Moats, dfAcclGoodMoats)

fitAcclM = list(S1 = sfConAcclM, S2 = sfWeightAcclM)
gpAcclM <- ggsurvplot(fitAcclM, data = dfAcclGoodMoats, combine = TRUE,
                         risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                         censor = FALSE, size = 1.5,legend = "none", xlim = c(10,50),
                         xlab = "Time in days", ylab = "Survival Probability", 
                         title = "All Confirmed and Assumed Deaths (separated), 
      Functional MOATS, Post-Acclimation")
lines <-  c(rep(c("solid"),12),rep(c("dotted"),12))
gpAcclM$plot <- gpAcclM$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 24, y = 0.11, label = "Solid = Confirmed; Dotted = Assumed; Color group by MOATS")
gpAcclM

#Once more, with feeling, post acclimation, good MOATS, confirmed and assumed together
survTotalAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$totalDeathEvent, type = "right")
sfTotalAcclM = survfit(survTotalAccl ~ Moats, dfAcclGoodMoats)

fitTotalAcclM = list(S1 = sfConAcclM, S2 = sfTotalAcclM)
gpTotalAcclM <- ggsurvplot(fitTotalAcclM, data = dfAcclGoodMoats, combine = TRUE,
                         risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                         censor = FALSE, size = 1.5, xlim = c(10,50),
                         xlab = "Time in days", ylab = "Survival Probability", 
                         title = "Confirmed and Confirmed + Assumed Deaths, 
      Functional MOATS, Post-Acclimation")
lines <-  c(rep(c("solid"),12),rep(c("dotted"),12))
gpTotalAcclM$plot <- gpTotalAcclM$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 30, y = 1, label = "Solid = Confirmed; Dotted = Confirmed + Assumed; Color group by MOATS")
gpTotalAcclM
```

```{r Survival by treatment, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}

#Confirmed Deaths
survCon <- Surv(time = df$Day, event = df$confirmedDeathEvent, type = "right")
sfConAllTimeT <- survfit(survCon ~ treatment, df)

#Assumed Deaths
survWeight <- Surv(time = df$Day, df$assumedDeathEvent, type = "right")
sfWeightAllTimeT <- survfit(survWeight ~ treatment, df)

#Total Deaths
survTotal <- Surv(time = df$Day, df$totalDeathEvent, type = "right")
sfTotalAllTimeT <- survfit(survTotal ~ treatment, df)

#Plot just the confirmed deaths from the beginning
ggsurvplot(sfConAllTimeT, data = df, title = "All Confirmed Deaths, All Treatments, All Time")

#Plot all confirmed and assumed deaths from the beginning, but keep them separated
fitAllTimeT <- list(S1 = sfConAllTimeT, S2 = sfWeightAllTimeT)
gpAllTimeT <- ggsurvplot(fitAllTimeT, data = df, combine = TRUE,
                 risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                 censor = FALSE, size = 1.5,
                 xlab = "Time in days",ylab = "Survival Probability",
                 title = "All Confirmed & Assumed Deaths (separate)             
                          All Treatments, All Time")
lines <-  c(rep(c("solid"),4),rep(c("dotted"),4))
gpAllTimeT$plot <- gpAllTimeT$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 25, y = 0.25, label = "Solid = Confirmed; Dotted = Assumed; Color group by Treatments")
gpAllTimeT

#Plot all confirmed and assumed deaths from the beginning, but put them together
fitTotalT <- list(S1 = sfConAllTimeT, S2 = sfTotalAllTimeT)
gpTotalT <- ggsurvplot(fitTotalT, data = df, combine = TRUE,
                                  risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                                  censor = FALSE, size = 1.5,
                                  xlab = "Time in days",ylab = "Survival Probability",
                                  title = "All Confirmed & Assumed Deaths, All Treatments, All Time")
lines <-  c(rep(c("solid"),4),rep(c("dotted"),4))
gpTotalT$plot <- gpTotalT$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 25, y = 0.18, label = "Solid = Confirmed; Dotted = Confirmed+Assumed; Color group by Treatment")
gpTotalT

#Adjust for acclimation time, remove problematic MOATS and plot again
#dfAccl <- df[df$Day > 10,]
ggTotalAcclt <- dfAcclGoodMoats %>%
mutate(Day = Day-10)
dfAcclGoodMoats <- subset(ggTotalAcclt, Moats != 4 & Moats != 5 & Moats != 11)

survConAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$confirmedDeathEvent, type = "right")
sfConAcclT = survfit(survConAccl ~ treatment, dfAcclGoodMoats)

survWeightAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$assumedDeathEvent, type = "right")
sfWeightAcclM = survfit(survWeightAccl ~ treatment, dfAcclGoodMoats)

fitAcclT = list(S1 = sfConAcclT, S2 = sfWeightAcclM)
gpAcclT <- ggsurvplot(fitAcclT, data = dfAcclGoodMoats, combine = TRUE,
                         risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                         censor = FALSE, size = 1.5, xlim = c(10,50),
                         xlab = "Time in days", ylab = "Survival Probability", 
                         title = "All Confirmed and Assumed Deaths (separated), 
      Functional MOATS, Post-Acclimation")
lines <-  c(rep(c("solid"),3),rep(c("dotted"),3))
gpAcclT$plot <- gpAcclT$plot + scale_linetype_manual(values = lines) +
  geom_hline(yintercept = 0.5, linetype = 2) +
  annotate("text",x = 24, y = 0.11, label = "Solid = Confirmed; Dotted = Assumed; Color group by Treatment")
gpAcclT

#Once more, with feeling, post acclimation, good MOATS, confirmed and assumed together

#Assign colorblind palette
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#999999",
          "#E69F00", "#56B4E9")


#Then continue as normal
survTotalAccl = Surv(time = dfAcclGoodMoats$Day, dfAcclGoodMoats$totalDeathEvent, type = "right")
sfTotalAcclT = survfit(survTotalAccl ~ treatment, dfAcclGoodMoats)

fitTotalAcclT = list(S1 = sfConAcclT, S2 = sfTotalAcclT)
gpTotalAcclT <- ggsurvplot(fitTotalAcclT, data = dfAcclGoodMoats, combine = TRUE,
                         risk.table = FALSE, pval = FALSE, conf.int = FALSE, linetype = "strata",
                         censor = FALSE, legend = "none",  size = 1.5, xlim = c(0,40),
                         xlab = "Time in days", ylab = "Survival Probability", 
                         title = "Confirmed and Confirmed + Assumed Deaths, 
      Functional MOATS, Post-Acclimation")
lines <-  c(rep(c("solid"),3),rep(c("dotted"),3))
gpTotalAcclT$plot <- gpTotalAcclT$plot + scale_linetype_manual(values = lines) + 
  scale_colour_manual(values=cbp1) 
  
gpTotalAcclT


```

```{r Cox models, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#Make treatment column a factor instead of a character
dfAcclGoodMoats$treatment <- factor(dfAcclGoodMoats$treatment)

#Cox proportional hazard model
coxTreatAll <- coxph(survTotalAccl ~ treatment, data = dfAcclGoodMoats)
summary(coxTreatAll)

#Mixed effect by treatment with MOATS as a random effect
coxMixedAll <- coxme(survTotalAccl ~ treatment + (1|Moats), data = dfAcclGoodMoats)
summary(coxMixedAll)

#Reorder to get all comparisons
dfAcclGoodMoats$treatment <-  fct_relevel(dfAcclGoodMoats$treatment, "Current")
  
#coxph again
coxTreatCurrent <- coxph(survTotalAccl ~ treatment, data = dfAcclGoodMoats)
summary(coxTreatCurrent)

#coxme again
coxMixedCurrent <- coxme(survTotalAccl ~ treatment + (1|Moats), data = dfAcclGoodMoats)
summary(coxMixedCurrent)
```

